# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Android

# Note that you have to bump the versionCode in android/app/build.gradle 

on:
  push:
    branches: [ android ]
  pull_request:
    branches: [ android ]


jobs:
  build:
    name: Build App Release Signed Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
            distribution: 'zulu'
            java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Ionic CLI
        run: sudo npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Build app
        run: ionic build --prod

      - name: Capacitor update
        run: npx cap update

      - name: Capacitor copy
        run: npx cap copy

      - name: Build app bundle
        run: cd android && gradle bundle

      - name: Extract Android signing key from env
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/MacrozillaKeyStore.jks.base64
          base64 -d android/MacrozillaKeyStore.jks.base64 > android/MacrozillaKeyStore.decrypted.jks

      - name: Sign dev build
        run: jarsigner -keystore android/MacrozillaKeyStore.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab macrozillakey

      - name: Upload release bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: android/app/build/outputs/bundle/release/app-release-signed.aab
          retention-days: 60
