# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Debug APK

# Note that you have to bump the versionCode in android/app/build.gradle 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
            distribution: 'zulu'
            java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Ionic CLI
        run: sudo npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Run config (Set envs)
        run: npm run config
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}

      - name: Build app
        run: ionic build --prod --configuration prodAndroid --release

      - name: Capacitor update
        run: npx cap update

      - name: Capacitor copy
        run: npx cap copy

      - name: Build app assembleDebug apk
        run: cd android && gradle assembleDebug 

      - name: Upload debug apk
        uses: actions/upload-artifact@v2
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 60
