# Firebase deploy
name: Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo npm install -g @ionic/cli
    - name: npm install, Run config (Set envs), build prod
      run: |
        npm install
        npm run config
        ionic build --prod --configuration prodWeb --release
      env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
    - name: Archive Build
      uses: actions/upload-artifact@v4
      with:
        name: public 
        path: public # The name of the public folder from firebase
        
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: public
          path: public
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_THEMACRODIET_S }}
          channelId: live
          projectId: themacrodiet-s
