# Firebase deploy
name: Firebase CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo npm install -g @ionic/cli
    #- run: sudo npm install -g @angular/cli
    - name: npm install, Run config (Set envs), build prod
      run: |
        npm install
        npm run config
        ionic build --prod --configuration prodWeb --release
      env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
    - name: Archive Build
      uses: actions/upload-artifact@v2
      with:
        name: www 
        path: www # The name of the public folder from firebase
        
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: www
          path: www
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_THEMACRODIET_S }}
